version: '3.9'

services:
  #new service (java_app)
  java_app:
    container_name: java_app
    image: event-streaming:1.0.0
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  #old service (postgres)
  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: {}